#!/usr/bin/env sh
set -xue ;
docker images | awk '{print $3}' | xargs docker rmi -f "$@" ;
docker images | awk '{print $3}' | xargs docker rmi -f "$@" ;
docker images | awk '{print $3}' | xargs docker rmi -f "$@" ;
