#!/usr/bin/env sh
set -xue ;
for DPATH in ./*/ ; do
  cd ${DPATH} ;
  echo "Directory : ${DPATH%*/}" ;
  git remote update --prune ;
  git checkout main ;
  git reset --hard origin/main ;
  "$@" ;
  echo "" ;
  cd .. ;
done ;
