#!/usr/bin/env sh
set -xue ;
if ls --color . > "/dev/null" 2>&1 ; then
  ls --color -hla "$@" ; # gnu
elif ls -G -d . > "/dev/null" 2>&1 ; then
  ls -Ghla "$@" ; # bsd
else
  ls -hla ; # solaris
fi ;
