#!/usr/bin/env sh
set -xue ;
if ls --color . > "/dev/null" 2>&1 ; then
  ls --color -hRla "$@" ; # gnu
elif ls -G -d . > "/dev/null" 2>&1 ; then
  ls -GhRla "$@" ; # bsd
else
  ls -hRla ; # solaris
fi ;
