#!/usr/bin/env sh
set -xue ;
if ls --color . > "/dev/null" 2>&1 ; then
  ls --color -hlat "$@" ; # gnu
elif ls -G -d . > "/dev/null" 2>&1 ; then
  ls -Ghlat "$@" ; # bsd
else
  ls -hlat ; # solaris
fi ;
