#!/usr/bin/env sh
set -xue ;
if ls --color . > "/dev/null" 2>&1 ; then
  ls --color -hRlat "$@" ; # gnu
elif ls -G -d . > "/dev/null" 2>&1 ; then
  ls -GhRlat "$@" ; # bsd
else
  ls -hRlat ; # solaris
fi ;
