#!/usr/bin/env sh
set -xue ;
if ls --color . > "/dev/null" 2>&1 ; then
  ls --color -hRl "$@" ; # gnu
elif ls -G -d . > "/dev/null" 2>&1 ; then
  ls -GhRl "$@" ; # bsd
else
  ls -hRl ; # solaris
fi ;
