#!/usr/bin/env sh
set -xue ;
if ls --color . > "/dev/null" 2>&1 ; then
  ls --color -hlt "$@" ; # gnu
elif ls -G -d . > "/dev/null" 2>&1 ; then
  ls -Ghlt "$@" ; # bsd
else
  ls -hlt ; # solaris
fi ;
