#!/usr/bin/env sh
set -xue ;
if ls --color . > "/dev/null" 2>&1 ; then
  ls --color -hRlt "$@" ; # gnu
elif ls -G -d . > "/dev/null" 2>&1 ; then
  ls -GhRlt "$@" ; # bsd
else
  ls -hRlt ; # solaris
fi ;
