#!/usr/bin/env sh
set -xue ;
EKEYS="$1" ;
PATHS="$2" ;

ARCHIVE="${PATHS}.tgz" ;
ARCHIVE_e="${PATHS}.tgz.aes" ;
PASSW="${PATHS}.pw" ;
PASSW_e="${PATHS}.pw.aes" ;

# command #
tar -czvf "${ARCHIVE}" "${PATHS}" ;
openssl rand -base64 256 -out "${PASSW}" ;
openssl enc -aes256 -salt -e -k "file:${PASSW}" -in "${ARCHIVE}" -out "${ARCHIVE_e}" ;
openssl rsautl -encrypt -pubin -inkey "${EKEYS}" -in "${PASSW}" -out "${PASSW_e}" ;

# clean #
rm -rf "${ARCHIVE}" ;
rm -rf "${PASSW}" ;
